### ISSUE TITLE
Incorrect action name in the readme file

### ISSUE THREAD

**Issue by jacek-marchwicki** [matco/action-connectiq-tester#1]
At the starting point, thank you for your work!

We can read in the [README](https://github.com/marketplace/actions/connectiq-tester) text as follows:

```yaml
- name: Test application
  id: run_tests
  uses: matco/connectiq-tester@v1
  with:
    device: fenix5
```

but instead of `matco/connectiq-tester` we should type `matco/action-connectiq-tester`
